global_options:
  json_serializable:
    runs_before:
      - retrofit_generator

targets:
  $default:
    sources:
      - $package$
      - lib/**
      - pubspec.yaml
      - test/**
    builders:
      flutter_gen_runner: # or flutter_gen
        options:
          output: lib/src/core/constant/assets/
          parse_metadata: true
          line_length: 80
          integrations:
            flutter_svg: true
      freezed:
        enabled: true
        generate_for:
          include:
            - lib/**
            - test/**
        options:
          build_extensions:
            '^lib/{{dir}}/{{file}}.dart': 'lib/{{dir}}/_generated/{{file}}.freezed.dart'
            '^test/{{dir}}/{{file}}.dart': 'test/{{dir}}/_generated/{{file}}.freezed.dart'
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/**
            - test/**
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{dir}}/{{file}}.dart': 'lib/{{dir}}/_generated/{{file}}.g.dart'
            '^test/{{dir}}/{{file}}.dart': 'test/{{dir}}/_generated/{{file}}.g.dart'