name: kitty_app
description: "The kitty app."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  ### Flutter SDK
  flutter:
    sdk: flutter
  collection: any
  async: any
  meta: any
  intl: any
  flutter_localizations:
    sdk: flutter

  ### Widgets
  cupertino_icons: ^1.0.8

  ### Input
  #  mask_text_input_formatter: ^2.9.0
  #  flutter_keyboard_visibility: ^6.0.0

  ### Images
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.0.17

  ### Text
  google_fonts: ^6.2.1

  ### BLoC
  flutter_bloc: ^9.1.0
  bloc_concurrency: ^0.3.0

  ### Navigation
  go_router: ^14.8.1

  ### Other
  #  equatable: ^2.0.7
  #  event_bus: ^2.0.1

  ### Networking
  dio: ^5.8.0

  ### Codegen
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  retrofit: ^4.4.2

  ### Storing data
  # shared_preferences: ^2.5.2
  # flutter_secure_storage: ^9.2.4
  # drift: ^2.26.0
  # drift_flutter: ^0.2.4

  ### Utils
  package_info_plus: ^8.3.0
  permission_handler: ^11.4.0
  clock: any
  path: any
  path_provider: ^2.1.5
  flutter_file_dialog: ^3.0.2
  # image_gallery_saver: ^2.0.3
  gallery_saver_plus: ^3.2.4

  ### Logging & Development
  logger: ^2.5.0
  device_preview: ^1.2.0
  stack_trace: any
  talker_dio_logger: ^4.7.1
  talker_bloc_logger: ^4.7.1
  talker_flutter: ^4.7.1

dev_dependencies:
  ### Testing
  flutter_test:
    sdk: flutter

  ### Utils
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5

  ### Codegen
  build_runner: ^2.4.15
  retrofit_generator: ^9.1.9
  json_serializable: ^6.9.4
  freezed: ^2.5.7
  go_router_builder: ^2.8.2

  ### Lints
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  # https://www.freepik.com/search?format=search&iconType=sticker&last_filter=iconType&last_value=sticker&query=cat&type=icon
  assets:
    - assets/platform/logo/
    - assets/platform/splash/
    - assets/images/
